version: '3'
services:
  mysql-learn-db:
    container_name: mysql-learn-db
    image: "mysql"
    env_file: ./db.env
    expose:
      - 3306
  web:
    build: .
    container_name: rails
    ports:
      - "3000:3000"
    volumes:
      - .:/learn
    depends_on:
      - mysql-learn-db
