version: '3'
services:
  learn-mysql:
    container_name: learn-mysql
    image: "mysql"
    env_file: ./db.env
    expose:
      - 3306
  learn-rails:
    build: .
    container_name: learn-rails
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/learn
    depends_on:
      - learn-mysql
